language: php

sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

services:
  - mysql

before_script: "ant -logger org.apache.tools.ant.NoBannerLogger db:initialize composer:composer"
script: "php vendor/bin/behat && php vendor/bin/phpunit"

branches:
    only:
        - master

cache:
    directories:
        - .npm
        - .pear
        - .abc
        - vendor
